This note book contains example code found in the book [Deep Learning Models: A Practical Approach for Hands-On Professionals] It is intended to aid the quick execution of of the examples while much of the details are remain in the book.

# Chapter 2.	Requirements for Hands on Approach to Deep Learning

## 2.1	Introduction

In this chapter we introduce some of the concepts needed to start build-ing deep learning models in Python. We will start with basic principles re-lated to data manipulation and end with explanation on how to set up the modelling environment. Of course, this chapter is not meant to replace any detailed course on Python but be a stepping stone for those already familiar or new to data structures in Python.  We would recommend to visit the  https://www.python.org/ site for comprehensive material Python. There is also vast number of online material both text and video on the Internet to help quicken the learning process.

## 2.2	Basic Python Arrays for Deep Learning

In deep learning models we will be processing data in numerical format defined from Python’s Numpy library. Therefore, for our purposes we will treat tensors as multidimensional Numpy arrays [1]. Why tensors? The Tensflow library is specifically geared to perform operations on tensors and tensors have the attractive property of being able to be efficiently manipu-lated on GPU. In deep learning, GPU processing drastically makes opera-tions faster reducing required time from hours to minutes.  

### Scalars and 1-D Arrays (Vector)

Scalar Example:

In [2]:
# Import the numpy library for array operations
import numpy as np

# Create a scalar (also know as 0-dimensional array or 0-D tensor)
ar1 = np.array(28)
print(ar1)

28


In [3]:
# Array contents can simply be confirmed by typing the array name
ar1

array(28)

Some of the commonly used important attributes of arrays include shape, dimension, size and data type. These can be queried by executing command of the type arrayname.attribute. In addition, arithmetic operations such as addition, multiplcation, transposition, etc. can be performed on arrays. Finally, array conversions and manipulations of shapes  arrays are also possible. We will give some examples of basic manipulation of matrices relevant to the scope of this book. These examples are in no way exhaustive and the we advise to quickly Google search for any topics of interest on arrays.  

1-D Array Example:

In [22]:
ar1 = np.array([1,2,3])
print(ar1)

[1 2 3]


In [23]:
# test
ar2 = np.array([
    [1],[2],[3]])

In [24]:
ar2.size

3

In [25]:
# Query array dimension => Expected answer is 1 for 1-D arrays or vectors or 1-D tensor. 
# In tensor terminology, the dimension is referred to as the aaxis.
ar1.ndim

1

In [32]:
# Query array shape => Here the expected answer is the number of elements along the axis, 3 in this case.
ar1.shape

(3,)

In [27]:
# Query array data type => Expected answer is "int32" for scalars since this is default type for integer elements if data type is not explicitly defined in the array.
ar1.dtype

dtype('int32')

In [31]:
# Query array size => Expected answer is "1" in the above example since the the size gives the number of elements in the array.
ar1.size

3

### 2-D Arrays (Matrices) , 3-D Arrays (Data cubes) 

1-D Array Example:

In [11]:
ar1 = np.array([1,2,3])
print(ar1)

[1 2 3]


In [12]:
# Query array dimension => Expected answer is 1 for 1-D arrays or vectors or 1-D tensor.
ar1.ndim

1

In [6]:
# Query array shape => Expected answer is empty "()" for scalars
ar1.shape

()

In [8]:
# Query array data type => Expected answer is "int32" for scalars since this is default type if not explicitly defined in the array.
ar1.dtype

dtype('int32')

In [10]:
# Query array size => Expected answer is "1" in the above example since the the size gives the number of elements in the array.
ar1.size

1

2D Array Example

In [8]:
# Create an array of arbitray shape
# Import the numpy library for array operations
import numpy as np

ar1= np.array([[0,1,2,3,4],[10,11,12,13,14], [20,21,22,23,24]])
print(ar1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]


In [9]:
# Query array dimension => Expected answer is 2 for 2-D arrays or vectors or 2-D tensor.
ar1.ndim

2

In [10]:
# Query array shape => Expected answer is "(3,5)" for the above example.
ar1.shape

(3, 5)

3D Array Example

In [12]:
# Import the numpy library for array operations
import numpy as np
ar1 = np.array([[[0, 1, 2, 3, 4],
               [10, 11, 12, 13, 14],
               [20, 21, 22, 23, 24]],
              [[5, 6, 7, 8, 9],
               [15, 26, 17, 18, 19],
               [25, 26, 27, 28, 29]],
              [[30, 31, 32, 33, 34],
               [40, 41, 42, 43, 44],
               [50, 51, 52, 53, 54]]])
print(ar1)

[[[ 0  1  2  3  4]
  [10 11 12 13 14]
  [20 21 22 23 24]]

 [[ 5  6  7  8  9]
  [15 26 17 18 19]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [40 41 42 43 44]
  [50 51 52 53 54]]]


In [13]:
# Query array dimension => Expected answer is 3 for 3-D arrays or cubes or 3-D tensor (e.g. length,width, depth => 3D).
ar1.ndim

3

In [14]:
# Query array shape => Expected answer is "(3,3,5)" for the above example.
ar1.shape

(3, 3, 5)

### Multi-dimensional Arrays 

In [15]:
# Import the numpy library for array operations
import numpy as np
ar1 = np.array([[[[0, 1, 2, 3, 4],
               [10, 11, 12, 13, 14],
               [20, 21, 22, 23, 24]],
              [[5, 6, 7, 8, 9],
               [15, 26, 17, 18, 19],
               [25, 26, 27, 28, 29]],
              [[30, 31, 32, 33, 34],
               [40, 41, 42, 43, 44],
               [50, 51, 52, 53, 54]]], 
               [[[30, 31, 32, 33, 34],
               [40, 41, 42, 43, 44],
               [50, 51, 52, 53, 54]],
              [[5, 6, 7, 8, 9],
               [15, 26, 17, 18, 19],
               [25, 26, 27, 28, 29]],
              [[30, 31, 32, 33, 34],
               [40, 41, 42, 43, 44],
               [50, 51, 52, 53, 54]]]])
print(ar1)

[[[[ 0  1  2  3  4]
   [10 11 12 13 14]
   [20 21 22 23 24]]

  [[ 5  6  7  8  9]
   [15 26 17 18 19]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [40 41 42 43 44]
   [50 51 52 53 54]]]


 [[[30 31 32 33 34]
   [40 41 42 43 44]
   [50 51 52 53 54]]

  [[ 5  6  7  8  9]
   [15 26 17 18 19]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [40 41 42 43 44]
   [50 51 52 53 54]]]]


In [16]:
# Query array dimension => Expected answer is 4 for 4-D arrays or 4-D tensor (e.g. channel, length, width, depth => 4D).

ar1.shapear1.ndim

4

In [17]:
# Query array shape => Expected answer is "(2,3,3,5)" for the above example,

ar1.shape

(2, 3, 3, 5)

### Array Shape manipulation 

In [1]:
# Example of reshape and transpose operations that can be performed on Numpy arrays
# Import the numpy library for array operations
import numpy as np

# Create an array of arbitray shape
ar1= np.array([[0,1,2,3,4],[10,11,12,13,14], [20,21,22,23,24]])
print(ar1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]


In [2]:
# Query array shape => Expected answer is "(3,5)" for this example
ar1.shape

(3, 5)

In [3]:
# Change the shape of the array by reshaping
ar1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4, 10],
       [11, 12, 13],
       [14, 20, 21],
       [22, 23, 24]])

In [4]:
# Query array shape => Expected answer is "(5,3)" for this example
ar1.shape

(3, 5)

In [10]:
# Change the shape of the array by transposition
ar2 = np.transpose(ar1)
ar2

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24]])

In [11]:
# Query array shape => Expected answer is "(5,3)" for this example
ar2.shape

(5, 3)